import type React from 'react';
import type { ReactNode } from 'react';
import { AbsoluteFill, Sequence } from 'remotion';
import {
  AreaTrend, BarRank, BeeswarmStrip, BollingerBand, BoxWhisker, BumpChart, BulletChart, CalendarHeatmap, Candlestick,
  ChordDiagram, CohortRetention, CompareMatrix, DecompositionTree, DensityContour, DivergingBars, Distribution, Dumbbell,
  DotPlot, FlowDiagram, Flywheel, FormulaReveal, Funnel, GanttSchedule, GroupedBars, Heatmap, HexbinDensity, Histogram,
  IndexedLine, KPIStat, LineChart, LollipopChart, Marimekko, NetworkGraph, ParetoChart, PopulationPyramid, RadialTree,
  RangeBand, SankeyFlow, ScatterPlot, ScenarioFan, ShareStack, SlopeGraph, SmallMultiples, SparkTable, Sunburst, Timeline,
  TornadoSensitivity, Treemap, WaffleChart, Waterfall,
} from './chartlib';
import { INSIGHT_FONT, INSIGHT_TOKENS } from './tokens';

const CARD = 120;
export const BUSINESS_INSIGHT_ATLAS_TOTAL = CARD * 50;

const Card: React.FC<{ index: number; name: string; useWhen: string; children: ReactNode }> = ({ index, name, useWhen, children }) => (
  <div style={{ position: 'absolute', inset: 0, padding: '68px 120px 56px', display: 'flex', flexDirection: 'column', boxSizing: 'border-box' }}>
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 18 }}>
      <div style={{ color: INSIGHT_TOKENS.amber, fontFamily: INSIGHT_FONT.mono, fontSize: 20, letterSpacing: '0.14em' }}>BUSINESS INSIGHT / VISUAL GRAMMAR / {String(index + 1).padStart(2, '0')}</div>
      <div style={{ color: INSIGHT_TOKENS.muted, fontFamily: INSIGHT_FONT.mono, fontSize: 18 }}>{useWhen}</div>
    </div>
    <div style={{ flex: 1, minWidth: 0, minHeight: 0, display: 'flex', justifyContent: 'center', alignItems: 'center', overflow: 'hidden' }}>{children}</div>
    <div style={{ color: INSIGHT_TOKENS.muted, fontFamily: INSIGHT_FONT.mono, fontSize: 18, letterSpacing: '0.1em', marginTop: 12 }}>{name.toUpperCase()}</div>
  </div>
);

const EXAMPLES: readonly { name: string; useWhen: string; render: (duration: number) => ReactNode }[] = [
  { name: 'KPI Stat', useWhen: '用一个数建立问题', render: (d) => <KPIStat value="68" suffix="%" label="复购用户占比（样例）" delta={{ value: '同比 +6pt', direction: 'up' }} durationInFrames={d} /> },
  { name: 'Line Chart', useWhen: '连续趋势', render: (d) => <LineChart label="复购率（样例）" data={[31, 38, 43, 51, 58]} xLabels={['Q1', 'Q2', 'Q3', 'Q4', 'Q5']} durationInFrames={d} /> },
  { name: 'Bar Rank', useWhen: '单指标排序', render: (d) => <BarRank title="增长驱动的重要性（样例）" items={[{ label: '产品匹配', value: 86, accent: true }, { label: '供给效率', value: 72 }, { label: '内容分发', value: 64 }, { label: '渠道覆盖', value: 51 }]} durationInFrames={d} /> },
  { name: 'Dot Plot', useWhen: '精确位置与排序', render: (d) => <DotPlot title="客群 LTV（样例）" items={[{ label: '核心客群', value: 860, accent: true }, { label: '成长客群', value: 640 }, { label: '机会客群', value: 470 }, { label: '新客', value: 290 }]} unit=" 元" durationInFrames={d} /> },
  { name: 'Share Stack', useWhen: '组成结构', render: (d) => <ShareStack title="反馈信号构成（样例）" segments={[{ label: '交易', value: 38 }, { label: '搜索', value: 27 }, { label: '内容', value: 21 }, { label: '售后', value: 14 }]} durationInFrames={d} /> },
  { name: 'Bullet Chart', useWhen: '实际与目标', render: (d) => <BulletChart title="经营计划完成度（样例）" metrics={[{ label: '收入', actual: 72, target: 80, unit: '%', accent: true }, { label: '复购', actual: 61, target: 65, unit: '%' }, { label: '周转', actual: 49, target: 55, unit: ' 天' }]} durationInFrames={d} /> },
  { name: 'Waterfall', useWhen: '指标变化归因', render: (d) => <Waterfall title="毛利改善桥接（样例）" steps={[{ label: '起点', value: 45, kind: 'total' }, { label: '售价', value: 8 }, { label: '折扣', value: -5 }, { label: '履约', value: 4 }, { label: '终点', value: 52, kind: 'total' }]} unit=" pt" durationInFrames={d} /> },
  { name: 'Slope Graph', useWhen: '两期排名移动', render: (d) => <SlopeGraph title="品类贡献的两期变化（样例）" leftLabel="去年" rightLabel="今年" unit="%" series={[{ label: '女装', from: 24, to: 31, accent: true }, { label: '运动', from: 28, to: 26 }, { label: '配饰', from: 15, to: 21 }, { label: '美妆', from: 18, to: 16 }]} durationInFrames={d} /> },
  { name: 'Range Band', useWhen: '基准区间与异常', render: (d) => <RangeBand title="行业区间与当前值（样例）" unit=" 天" items={[{ label: '补货周期', low: 18, high: 32, actual: 22, accent: true }, { label: '库存周转', low: 35, high: 52, actual: 47 }, { label: '退货处理', low: 3, high: 9, actual: 5 }]} durationInFrames={d} /> },
  { name: 'Distribution', useWhen: '分布而非均值', render: (d) => <Distribution title="订单金额分布（样例）" bins={[{ label: '0-99', value: 18 }, { label: '100-199', value: 42 }, { label: '200-299', value: 67 }, { label: '300-399', value: 54 }, { label: '400-499', value: 33 }, { label: '500+', value: 21 }]} highlightIndex={2} durationInFrames={d} /> },
  { name: 'Dumbbell', useWhen: '成对变化比较', render: (d) => <Dumbbell title="策略前后的复购变化（样例）" beforeLabel="策略前" afterLabel="策略后" unit="%" items={[{ label: '会员', before: 42, after: 58, accent: true }, { label: '内容', before: 29, after: 39 }, { label: '搜索', before: 35, after: 44 }, { label: '门店', before: 31, after: 34 }]} durationInFrames={d} /> },
  { name: 'Funnel', useWhen: '阶段转化', render: (d) => <Funnel title="从触达到复购（样例）" stages={[{ label: '触达', value: 100, detail: '100k' }, { label: '浏览', value: 64, detail: '64%' }, { label: '加购', value: 31, detail: '31%' }, { label: '成交', value: 17, detail: '17%', accent: true }, { label: '复购', value: 8, detail: '8%' }]} unit="%" durationInFrames={d} /> },
  { name: 'Heatmap', useWhen: '二维模式扫描', render: (d) => <Heatmap title="内容 × 时段互动（样例）" rows={['短视频', '图文', '直播', '会员']} columns={['周一', '周二', '周三', '周四', '周五']} values={[[46, 62, 73, 55, 81], [31, 43, 51, 39, 54], [58, 71, 66, 84, 91], [22, 28, 34, 42, 48]]} durationInFrames={d} /> },
  { name: 'Timeline', useWhen: '时间与因果', render: (d) => <Timeline title="策略迭代时间线（样例）" events={[{ date: 'Q1', title: '建立指标', detail: '统一口径' }, { date: 'Q2', title: '小单试投', detail: '验证需求', accent: true }, { date: 'Q3', title: '补货协同', detail: '缩短响应' }, { date: 'Q4', title: '回收学习', detail: '复购反馈' }]} durationInFrames={d} /> },
  { name: 'Flow Diagram', useWhen: '线性决策流程', render: (d) => <FlowDiagram title="从信号到决策（样例）" steps={[{ id: '1', label: '捕捉信号', detail: '搜索与交易' }, { id: '2', label: '验证需求', detail: '小批量试投' }, { id: '3', label: '组织供给', detail: '采购协同' }, { id: '4', label: '回收学习', detail: '复购反馈' }]} durationInFrames={d} /> },
  { name: 'Sankey Flow', useWhen: '多对多流向', render: (d) => <SankeyFlow title="渠道到品类的流向（样例）" unit="%" nodes={[{ id: 'a', label: '搜索', side: 'left' }, { id: 'b', label: '内容', side: 'left' }, { id: 'c', label: '女装', side: 'right' }, { id: 'd', label: '运动', side: 'right' }, { id: 'e', label: '配饰', side: 'right' }]} links={[{ from: 'a', to: 'c', value: 26 }, { from: 'a', to: 'd', value: 17 }, { from: 'b', to: 'c', value: 20 }, { from: 'b', to: 'e', value: 13 }]} durationInFrames={d} /> },
  { name: 'Population Pyramid', useWhen: '双侧结构比较', render: (d) => <PopulationPyramid title="新客与复购客结构（样例）" leftLabel="新客" rightLabel="复购客" unit="%" rows={[{ label: '18-24', left: 34, right: 19 }, { label: '25-34', left: 48, right: 57 }, { label: '35-44', left: 27, right: 38 }, { label: '45+', left: 12, right: 24 }]} durationInFrames={d} /> },
  { name: 'Formula Reveal', useWhen: '把结论拆成变量', render: (d) => <FormulaReveal caption="所有变量均应可被追溯与复核" tokens={[{ text: '需求信号', type: 'term' }, { text: '×', type: 'operator' }, { text: '快速验证', type: 'term' }, { text: '=', type: 'operator' }, { text: '更低错配成本', type: 'result' }]} durationInFrames={d} /> },
  { name: 'Flywheel', useWhen: '循环反馈机制', render: (d) => <Flywheel nodes={['信号', '企划', '采购', '库存', '渠道', '回流']} durationInFrames={d} radius={270} /> },
  { name: 'Compare Matrix', useWhen: '可读的定性比较', render: (d) => <CompareMatrix columns={['模式 A', '模式 B', '模式 C']} rows={['需求信号', '供给节奏', '增长引擎']} cells={[["用户反馈", "投放测试", "会员行为"], ["小单快返", "柔性供给", "规模补货"], ["复购", "流量", "效率"]]} durationInFrames={d} /> },
  { name: 'Candlestick', useWhen: '区间与开收盘', render: (d) => <Candlestick title="月度毛利率波动（样例）" unit="%" candles={[{ label: '1月', open: 42, high: 48, low: 39, close: 46 }, { label: '2月', open: 46, high: 51, low: 44, close: 49 }, { label: '3月', open: 49, high: 50, low: 43, close: 45 }, { label: '4月', open: 45, high: 54, low: 44, close: 52 }, { label: '5月', open: 52, high: 56, low: 49, close: 54 }]} durationInFrames={d} /> },
  { name: 'Indexed Line', useWhen: '相对表现基准化', render: (d) => <IndexedLine title="相对增长表现（样例）" xLabels={['Q1', 'Q2', 'Q3', 'Q4', 'Q5']} series={[{ label: '品牌', values: [100, 109, 118, 126, 141], accent: true }, { label: '行业', values: [100, 105, 111, 116, 121] }, { label: '同类', values: [100, 103, 107, 114, 126] }]} durationInFrames={d} /> },
  { name: 'Bump Chart', useWhen: '排名随时间变化', render: (d) => <BumpChart title="品类排名变化（样例）" xLabels={['Q1', 'Q2', 'Q3', 'Q4']} series={[{ label: '女装', ranks: [2, 1, 1, 1], accent: true }, { label: '运动', ranks: [1, 2, 2, 3] }, { label: '配饰', ranks: [4, 3, 3, 2] }, { label: '美妆', ranks: [3, 4, 4, 4] }]} durationInFrames={d} /> },
  { name: 'Scatter Plot', useWhen: '变量相关性', render: (d) => <ScatterPlot title="价格与复购的关系（样例）" xLabel="客单价" yLabel="复购率" points={[{ label: '基础款', x: 180, y: 43, size: 21, accent: true }, { label: '运动', x: 260, y: 38, size: 16 }, { label: '配饰', x: 110, y: 27, size: 13 }, { label: '美妆', x: 320, y: 35, size: 17 }, { label: '设计师', x: 410, y: 29, size: 11 }]} durationInFrames={d} /> },
  { name: 'Waffle Chart', useWhen: '比例的单位感', render: (d) => <WaffleChart title="新客来源构成（样例）" segments={[{ label: '自然搜索', value: 42, accent: true }, { label: '内容种草', value: 31 }, { label: '付费投放', value: 19 }, { label: '推荐', value: 8 }]} durationInFrames={d} /> },
  { name: 'Marimekko', useWhen: '规模与组成同时比较', render: (d) => <Marimekko title="渠道规模 × 品类结构（样例）" columns={[{ label: '搜索', value: 43, segments: [{ label: '女装', value: 52 }, { label: '运动', value: 30 }, { label: '配饰', value: 18 }] }, { label: '内容', value: 31, segments: [{ label: '女装', value: 38 }, { label: '运动', value: 26 }, { label: '配饰', value: 36 }] }, { label: '会员', value: 26, segments: [{ label: '女装', value: 46 }, { label: '运动', value: 37 }, { label: '配饰', value: 17 }] }]} durationInFrames={d} /> },
  { name: 'Cohort Retention', useWhen: '留存分群', render: (d) => <CohortRetention title="新客队列留存（样例）" cohorts={['1月新客', '2月新客', '3月新客', '4月新客']} periods={['当月', 'M+1', 'M+2', 'M+3']} values={[[100, 46, 33, 27], [100, 49, 35], [100, 44], [100]]} durationInFrames={d} /> },
  { name: 'Small Multiples', useWhen: '多个趋势并读', render: (d) => <SmallMultiples title="品类趋势小倍图（样例）" xLabels={['Q1', 'Q2', 'Q3', 'Q4']} series={[{ label: '女装', values: [51, 58, 63, 70], accent: true }, { label: '运动', values: [43, 49, 52, 57] }, { label: '配饰', values: [28, 31, 36, 41] }, { label: '美妆', values: [35, 34, 39, 46] }, { label: '家居', values: [19, 22, 25, 26] }, { label: '奢品', values: [13, 17, 19, 24] }]} durationInFrames={d} /> },
  { name: 'Scenario Fan', useWhen: '预测区间与不确定性', render: (d) => <ScenarioFan title="收入情景区间（样例）" unit=" 亿" highlightFrom={2} points={[{ label: 'Q1', low: 10, median: 12, high: 14 }, { label: 'Q2', low: 12, median: 15, high: 18 }, { label: 'Q3E', low: 14, median: 18, high: 23 }, { label: 'Q4E', low: 16, median: 22, high: 30 }, { label: 'FY E', low: 19, median: 27, high: 38 }]} durationInFrames={d} /> },
  { name: 'Spark Table', useWhen: '紧凑的多指标财务看板', render: (d) => <SparkTable title="核心经营指标速览（样例）" rows={[{ label: 'GMV', value: '1.47 万亿', change: '+18%', values: [81, 92, 106, 119, 147], accent: true }, { label: '毛利率', value: '54%', change: '+4pt', values: [43, 45, 47, 50, 54] }, { label: '库存周转', value: '39 天', change: '−6 天', values: [52, 49, 46, 43, 39] }, { label: '复购率', value: '58%', change: '+7pt', values: [44, 46, 49, 54, 58] }]} durationInFrames={d} /> },
  { name: 'Area Trend', useWhen: '趋势中强调规模', render: (d) => <AreaTrend title="季度交易规模（样例）" values={[48, 57, 61, 79, 91]} labels={['Q1', 'Q2', 'Q3', 'Q4', 'Q5']} unit=" 亿" durationInFrames={d} /> },
  { name: 'Grouped Bars', useWhen: '多个指标横向比较', render: (d) => <GroupedBars title="区域经营效率（样例）" groups={[{ label: '华东', values: [{ label: '增长', value: 72 }, { label: '毛利', value: 58 }] }, { label: '华南', values: [{ label: '增长', value: 66 }, { label: '毛利', value: 63 }] }, { label: '华北', values: [{ label: '增长', value: 54 }, { label: '毛利', value: 47 }] }]} unit="%" durationInFrames={d} /> },
  { name: 'Diverging Bars', useWhen: '正负贡献并读', render: (d) => <DivergingBars title="满意度净变化（样例）" items={[{ label: '物流', value: 18, accent: true }, { label: '价格', value: 9 }, { label: '客服', value: -6 }, { label: '售后', value: -13 }]} unit=" pt" durationInFrames={d} /> },
  { name: 'Lollipop Chart', useWhen: '排序但减少柱体重量', render: (d) => <LollipopChart title="内容主题互动率（样例）" items={[{ label: '新品故事', value: 68, accent: true }, { label: '穿搭指南', value: 57 }, { label: '会员权益', value: 44 }, { label: '供应链', value: 31 }]} unit="%" durationInFrames={d} /> },
  { name: 'Pareto Chart', useWhen: '识别少数关键原因', render: (d) => <ParetoChart title="客诉原因优先级（样例）" items={[{ label: '尺码', value: 37, accent: true }, { label: '时效', value: 26 }, { label: '描述', value: 18 }, { label: '质量', value: 11 }, { label: '其他', value: 8 }]} durationInFrames={d} /> },
  { name: 'Box Whisker', useWhen: '中位数、离散度与异常值', render: (d) => <BoxWhisker title="门店客单价离散度（样例）" unit=" 元" items={[{ label: '旗舰店', min: 215, q1: 278, median: 336, q3: 412, max: 498, accent: true, outliers: [560] }, { label: '标准店', min: 138, q1: 195, median: 244, q3: 301, max: 372 }, { label: '社区店', min: 92, q1: 133, median: 164, q3: 208, max: 256 }]} durationInFrames={d} /> },
  { name: 'Histogram', useWhen: '连续分布与长尾', render: (d) => <Histogram title="订单金额长尾（样例）" unit=" 元" bins={[{ from: 0, to: 99, count: 23 }, { from: 100, to: 199, count: 61 }, { from: 200, to: 299, count: 78, highlight: true }, { from: 300, to: 399, count: 49 }, { from: 400, to: 499, count: 28 }, { from: 500, to: 699, count: 14 }]} durationInFrames={d} /> },
  { name: 'Beeswarm Strip', useWhen: '保留每个样本点', render: (d) => <BeeswarmStrip title="各店履约时长样本（样例）" unit=" 小时" groups={[{ label: '华东', values: [18, 21, 23, 24, 25, 28, 33], accent: true }, { label: '华南', values: [20, 22, 25, 27, 29, 31] }, { label: '华北', values: [24, 25, 28, 32, 35] }]} durationInFrames={d} /> },
  { name: 'Hexbin Density', useWhen: '大样本二维密度', render: (d) => <HexbinDensity title="价格 × 复购密度（样例）" xLabel="客单价" yLabel="复购率" cells={[{ x: .12, y: .18, value: 12 }, { x: .28, y: .34, value: 27 }, { x: .42, y: .37, value: 44 }, { x: .58, y: .55, value: 69 }, { x: .7, y: .56, value: 38 }, { x: .72, y: .73, value: 19 }, { x: .84, y: .78, value: 10 }]} durationInFrames={d} /> },
  { name: 'Density Contour', useWhen: '识别聚集与热点轮廓', render: (d) => <DensityContour title="客户价值的聚集区（样例）" xLabel="消费频率" yLabel="客单价" levels={[{ cx: .32, cy: .4, rx: 220, ry: 128 }, { cx: .32, cy: .4, rx: 145, ry: 84, color: '#C99942', label: '核心' }, { cx: .72, cy: .7, rx: 145, ry: 88, label: '高客单' }]} durationInFrames={d} /> },
  { name: 'Bollinger Band', useWhen: '趋势与波动带', render: (d) => <BollingerBand title="周度需求与波动区间（样例）" points={[{ label: 'W1', value: 74, mean: 70, low: 61, high: 80 }, { label: 'W2', value: 80, mean: 74, low: 64, high: 85 }, { label: 'W3', value: 78, mean: 77, low: 68, high: 87 }, { label: 'W4', value: 92, mean: 82, low: 72, high: 94 }, { label: 'W5', value: 88, mean: 86, low: 75, high: 97 }]} durationInFrames={d} /> },
  { name: 'Tornado Sensitivity', useWhen: '假设的影响排序', render: (d) => <TornadoSensitivity title="估值敏感性（样例）" drivers={[{ label: '复购率', downside: -18, upside: 24 }, { label: '毛利率', downside: -15, upside: 17 }, { label: '获客成本', downside: -12, upside: 9 }, { label: '库存周转', downside: -7, upside: 8 }]} durationInFrames={d} /> },
  { name: 'Decomposition Tree', useWhen: '经营指标的下钻归因', render: (d) => <DecompositionTree title="GMV 的指标拆解（样例）" nodes={[{ id: 'gmv', label: 'GMV', value: '100', accent: true }, { id: 'traffic', label: '流量', value: '+18%', parent: 'gmv' }, { id: 'cvr', label: '转化', value: '+4pt', parent: 'gmv' }, { id: 'search', label: '搜索', value: '+11%', parent: 'traffic' }, { id: 'content', label: '内容', value: '+7%', parent: 'traffic' }, { id: 'price', label: '客单价', value: '+2%', parent: 'cvr' }]} durationInFrames={d} /> },
  { name: 'Treemap', useWhen: '层级组合的规模比较', render: (d) => <Treemap title="品类组合规模（样例）" tiles={[{ label: '女装', value: 42, accent: true }, { label: '运动', value: 24 }, { label: '配饰', value: 16 }, { label: '美妆', value: 11 }, { label: '家居', value: 7 }]} durationInFrames={d} /> },
  { name: 'Sunburst', useWhen: '逐层展示组成结构', render: (d) => <Sunburst title="收入 → 品类 → 子品类（样例）" rings={[{ label: '收入', segments: [{ label: '女装', value: 46, accent: true }, { label: '运动', value: 31 }, { label: '配饰', value: 23 }] }, { label: '子品类', segments: [{ label: '连衣裙', value: 24, accent: true }, { label: 'T恤', value: 22 }, { label: '跑鞋', value: 17 }, { label: '瑜伽', value: 14 }, { label: '包袋', value: 23 }]}]} durationInFrames={d} /> },
  { name: 'Radial Tree', useWhen: '深层父子关系', render: (d) => <RadialTree title="供应网络层级（样例）" nodes={[{ id: 'hq', label: '总部', accent: true }, { id: 'east', label: '华东', parent: 'hq' }, { id: 'south', label: '华南', parent: 'hq' }, { id: 'e1', label: '成衣', parent: 'east' }, { id: 'e2', label: '物流', parent: 'east' }, { id: 's1', label: '鞋服', parent: 'south' }, { id: 's2', label: '仓储', parent: 'south' }]} durationInFrames={d} /> },
  { name: 'Network Graph', useWhen: '生态与依赖关系', render: (d) => <NetworkGraph title="生态合作关系（样例）" nodes={[{ id: 'brand', label: '品牌', x: .48, y: .47, size: 1.5, accent: true }, { id: 'content', label: '内容', x: .18, y: .2 }, { id: 'creator', label: '创作者', x: .13, y: .74 }, { id: 'supply', label: '供给', x: .77, y: .18, size: 1.15 }, { id: 'logistics', label: '履约', x: .85, y: .68 }, { id: 'member', label: '会员', x: .53, y: .88 }]} links={[{ from: 'brand', to: 'content', value: 3 }, { from: 'brand', to: 'creator', value: 2 }, { from: 'brand', to: 'supply', value: 4 }, { from: 'brand', to: 'logistics', value: 3 }, { from: 'brand', to: 'member', value: 4 }, { from: 'content', to: 'member', value: 2 }]} durationInFrames={d} /> },
  { name: 'Chord Diagram', useWhen: '少量类别的双向流动', render: (d) => <ChordDiagram title="客群迁移流向（样例）" nodes={[{ id: 'new', label: '新客', accent: true }, { id: 'member', label: '会员' }, { id: 'repeat', label: '复购' }, { id: 'lost', label: '流失' }]} links={[{ from: 'new', to: 'member', value: 9 }, { from: 'member', to: 'repeat', value: 12 }, { from: 'repeat', to: 'member', value: 6 }, { from: 'new', to: 'lost', value: 5 }, { from: 'repeat', to: 'lost', value: 3 }]} durationInFrames={d} /> },
  { name: 'Gantt Schedule', useWhen: '排期、产能与进度', render: (d) => <GanttSchedule title="新品上市协同排期（样例）" periods={['1月', '2月', '3月', '4月', '5月']} tasks={[{ label: '需求验证', group: '产品', start: 0, end: 1.3, progress: 1, accent: true }, { label: '小单测试', group: '供给', start: .8, end: 2.1, progress: .76 }, { label: '渠道预热', group: '营销', start: 1.8, end: 3.2, progress: .45 }, { label: '正式上市', group: '销售', start: 3, end: 4, progress: .1 }]} durationInFrames={d} /> },
  { name: 'Calendar Heatmap', useWhen: '日级节奏与异常日', render: (d) => <CalendarHeatmap title="近六周交易活跃度（样例）" weeks={6} cells={Array.from({ length: 42 }, (_, i) => ({ label: `第${Math.floor(i / 7) + 1}周-${i % 7 + 1}`, week: Math.floor(i / 7), day: i % 7, value: [26, 38, 51, 44, 69, 83, 57][i % 7] + Math.floor(i / 7) * 4 }))} durationInFrames={d} /> },
];

export const BusinessInsightAtlas: React.FC = () => <AbsoluteFill style={{ background: `radial-gradient(circle at 50% 5%, #1B2636 0%, ${INSIGHT_TOKENS.bg} 54%)` }}>
  {EXAMPLES.map((example, index) => <Sequence key={example.name} from={index * CARD} durationInFrames={CARD}><Card index={index} name={example.name} useWhen={example.useWhen}>{example.render(CARD)}</Card></Sequence>)}
</AbsoluteFill>;
