import { useCurrentFrame } from 'remotion';
import { reveal } from './chart-utils';
import { INSIGHT_FONT, INSIGHT_TOKENS } from '../tokens';

export type DecompositionNode = { id: string; label: string; value: string; parent?: string; accent?: boolean };
export type DecompositionTreeProps = { title: string; nodes: DecompositionNode[]; durationInFrames: number };

/** Metric root-cause tree; use when a single outcome is explained through successive business dimensions. */
export const DecompositionTree: React.FC<DecompositionTreeProps> = ({ title, nodes, durationInFrames: _durationInFrames }) => {
  const frame = useCurrentFrame(); const roots = nodes.filter((node) => !node.parent); const maxDepth = Math.max(...nodes.map((node) => { let depth = 0; let current = node; while (current.parent) { depth += 1; current = nodes.find((entry) => entry.id === current.parent) ?? { ...current, parent: undefined }; } return depth; })); const positions = new Map<string, { x: number; y: number; depth: number }>();
  nodes.forEach((node, index) => { let depth = 0; let current = node; while (current.parent) { depth += 1; current = nodes.find((entry) => entry.id === current.parent) ?? { ...current, parent: undefined }; } const atDepth = nodes.filter((entry) => { let d = 0; let c = entry; while (c.parent) { d += 1; c = nodes.find((candidate) => candidate.id === c.parent) ?? { ...c, parent: undefined }; } return d === depth; }); const order = atDepth.findIndex((entry) => entry.id === node.id); positions.set(node.id, { x: 170 + depth / Math.max(maxDepth, 1) * 1120, y: 200 + order / Math.max(atDepth.length - 1, 1) * 340, depth }); });
  return <svg viewBox="0 0 1500 720" style={{ width: 1500, height: 720 }}><text x="90" y="58" fill={INSIGHT_TOKENS.text} fontFamily={INSIGHT_FONT.serif} fontSize="48">{title}</text>{nodes.filter((node) => node.parent).map((node) => { const from = positions.get(node.parent!); const to = positions.get(node.id); return from && to ? <path key={`${node.parent}-${node.id}`} d={`M ${from.x + 120} ${from.y} C ${from.x + 220} ${from.y}, ${to.x - 120} ${to.y}, ${to.x - 120} ${to.y}`} stroke={INSIGHT_TOKENS.line} fill="none" strokeWidth="3" /> : null; })}{nodes.map((node, index) => { const p = positions.get(node.id)!; const progress = reveal(frame, 8 + p.depth * 15 + index * 4, 16); return <g key={node.id} opacity={progress}><rect x={p.x - 120} y={p.y - 42} width="240" height="84" rx="7" fill={node.accent ? INSIGHT_TOKENS.amber : INSIGHT_TOKENS.surfaceElevated} stroke={node.accent ? INSIGHT_TOKENS.amberSoft : INSIGHT_TOKENS.line} /><text x={p.x} y={p.y - 7} textAnchor="middle" fill={node.accent ? INSIGHT_TOKENS.bg : INSIGHT_TOKENS.text} fontFamily={INSIGHT_FONT.sans} fontSize="20">{node.label}</text><text x={p.x} y={p.y + 20} textAnchor="middle" fill={node.accent ? INSIGHT_TOKENS.bg : INSIGHT_TOKENS.muted} fontFamily={INSIGHT_FONT.mono} fontSize="18">{node.value}</text></g>; })}{roots.length ? null : null}</svg>;
};
