import { useCurrentFrame } from 'remotion';
import { reveal } from './chart-utils';
import { INSIGHT_FONT, INSIGHT_TOKENS } from '../tokens';

export type SparkRow = { label: string; value: string; change?: string; values: number[]; accent?: boolean };
export type SparkTableProps = { title: string; rows: SparkRow[]; durationInFrames: number; valueLabel?: string; trendLabel?: string };

/** Compact editorial table with aligned sparklines for comparing many financial or operating metrics at once. */
export const SparkTable: React.FC<SparkTableProps> = ({ title, rows, durationInFrames: _durationInFrames, valueLabel = '最新值', trendLabel = '趋势' }) => {
  const frame = useCurrentFrame();
  return <div style={{ width: 1460 }}><h2 style={{ color: INSIGHT_TOKENS.text, fontFamily: INSIGHT_FONT.serif, fontSize: 52, fontWeight: 500, margin: '0 0 32px' }}>{title}</h2><div style={{ display: 'grid', gridTemplateColumns: '250px 220px 1fr 180px', gap: 24, padding: '0 0 14px', borderBottom: `1px solid ${INSIGHT_TOKENS.line}`, color: INSIGHT_TOKENS.muted, fontFamily: INSIGHT_FONT.mono, fontSize: 19 }}><span>指标</span><span>{valueLabel}</span><span>{trendLabel}</span><span style={{ textAlign: 'right' }}>变化</span></div>{rows.map((row, index) => { const progress = reveal(frame, 8 + index * 13, 18); const min = Math.min(...row.values); const max = Math.max(...row.values); const points = row.values.map((value, pointIndex) => ({ x: 8 + pointIndex / Math.max(row.values.length - 1, 1) * 610, y: 54 - (value - min) / Math.max(max - min, 1) * 44 })); const path = points.map((point, pointIndex) => `${pointIndex ? 'L' : 'M'} ${point.x} ${point.y}`).join(' '); const positive = (row.values[row.values.length - 1] ?? 0) >= (row.values[0] ?? 0); const color = row.accent ? INSIGHT_TOKENS.amber : positive ? INSIGHT_TOKENS.green : INSIGHT_TOKENS.red; return <div key={row.label} style={{ display: 'grid', gridTemplateColumns: '250px 220px 1fr 180px', gap: 24, alignItems: 'center', height: 92, opacity: progress, borderBottom: `1px solid ${INSIGHT_TOKENS.line}` }}><span style={{ color: INSIGHT_TOKENS.text, fontFamily: INSIGHT_FONT.sans, fontSize: 26 }}>{row.label}</span><span style={{ color: INSIGHT_TOKENS.text, fontFamily: INSIGHT_FONT.mono, fontSize: 25 }}>{row.value}</span><svg viewBox="0 0 630 62" style={{ width: '100%', height: 62 }}><line x1="0" x2="630" y1="56" y2="56" stroke={INSIGHT_TOKENS.line} /><path d={path} fill="none" stroke={color} strokeWidth="4" strokeLinecap="round" /></svg><span style={{ color, fontFamily: INSIGHT_FONT.mono, fontSize: 23, textAlign: 'right' }}>{row.change ?? '—'}</span></div>; })}</div>;
};
